### ISSUE TITLE
DsCommand | Can not compare DsCommand<dynamic> and DsCommand<T> when all fields are same

### ISSUE THREAD

**Issue by Minyewoo** [a-givertzman/hmi_core#18]
`DsCommand` has `runtimeType` check in its comparison operator: `other.runtimeType == runtimeType `.
If we have 2 identical `DsCommand` instances (for example `DsCommand<int>`), but second was upcasted to `DsCommand<dynamic>` (while iterating an array of commands, for example), then first command is no longer equal to the second one.

As an option, we can remove  `runtimeType` check.

**Comment by a-givertzman** [comment]
Let's leave it as it, we can remove runtimeType check when it become an any real problem.
Rewrite unit tests to avoid this point for now.
