### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/hmi_core#3]

**Comment by Minyewoo** [comment]
- [ ] DsCommand
    - [ ] fromJson
        - [ ] fails with incorrect string
        - [ ] completes with correct string
    - [ ] toJson
    - [ ] operator ==
- [ ] DsDataClass
    - [ ] fromString
- [ ] DsDataPoint
    - [ ] toJson
- [ ] DsDataType
    - [ ]  fromString
- [ ] DsStatus
    - [ ] fromString
    - [ ] fromValue
- [ ] DsTimeStamp
    - [ ] parse
    - [ ] toString
    - [ ] operator ==
- [ ] Result
    - [ ] data
    - [ ] error
    - [ ] hasData
    - [ ] hasError
    - [ ] fold

**Comment by a-givertzman** [comment]
@Minyewoo: Возможно, в геттере hasData ошибка, но это может быть и фичей

**Comment by Minyewoo** [comment]
> @Minyewoo: Возможно, в геттере hasData ошибка, но это может быть и фичей

Геттер `hasData` пытается получить данные из другого геттера `data` и проверить их на `null`, но при `null` `data` выбрасывает исключение. Скорее всего, тут нужно проверять на `null` приватную переменную `_data`, по аналогии с тем, как это сделано в геттере `hasError`.
